title: "My MD Blog"
description: "Markdown notes and docs"
theme: jekyll-theme-minimal
baseurl: "/blog"
url: "https://YOUR_ID.github.io"
lang: "ko"
markdown: kramdown
repository_url: "https://github.com/YOUR_ID/blog"
home_label: "Go to Main"
show_downloads: false
defaults:
  - scope:
      path: ""
    values:
      layout: default
